title: Michael Kant
description: Michael Kant's blog and project site

url: http://michaelkant.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Projects
   url: /projects
 - title: Blog
   url: /blog
 - title: Contact
   url: /contact

social:
   github: inconsiderate
   twitter: michaelkant
   email: michaelkant@live.com

#google_analytics: "UA-58263416-1"
